### PR TITLE
Update AnagramSnippet.java

### PR DESCRIPTION
**Pull request by Abdullah8006**
Moved the array declaration after the if statement to minimise the unnecessary array creation in case the function returns from the if statement.

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
Please update the `README.md` accordingly

**Comment by Abdullah8006** [comment]
Updated https://github.com/iluwatar/30-seconds-of-java/pull/188

**Comment by iluwatar** [comment]
Could you put the related changes in the same PR, here?

**Comment by Abdullah8006** [comment]
@iluwatar Updated the README.md as well. Sorry for responding late.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

**Pull request merged**
