### PR TITLE
Hacktoberfest - add "move special characters to end" under strings

### PR DESCRIPTION
**Pull request by draco-malfoy**

### CODE REVIEW

**Comment by draco-malfoy** [comment]
@iluwatar @grzesiekkedzior Why does the build fail?

**Comment by swarajsaaj** [comment]
@draco-malfoy there are some checkstyle violations in the new class which is causing the build checks to fail (you can find them in build logs)

**Comment by grzesiekkedzior** [comment]
Your coding style is unacceptable. Indentations, variables, logical blocks... Could you explain me line 34 inside MoveSpecialCharsToEnd.java? Four separated PR? Did you read README file?
Please do the things carefully. Use gradle tools to check properly coding style, tests and so on. Then push it all.

**Comment by draco-malfoy** [comment]
@grzesiekkedzior thank you for the review, but I couldn't get about four separated PR, variables and logical blocks

**Comment by iluwatar** [comment]
@draco-malfoy the style rules are in `config/checkstyle.xml`. Try to import this to your IDE and it will do the correct styling for you.

Some quick Googling produced these guides

- http://biercoff.com/how-to-import-checkstyle-rules-into-intellij-idea-code-format-rules/
- https://www.vogella.com/tutorials/Checkstyle/article.html

**Pull request closed without merging**
