### PR TITLE
Solves issue #14: HTTP Post snippet

### LINKED ISSUE #14: Add HTTP Post
HTTP post in plain Java. Use of Java 11 HttpClient is preferred.

Links:
https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html

### PR DESCRIPTION
**Pull request by PalAditya**
Fixes #14 

You can check that the test passes from this local gradle build snippet 😄 
ilu

### CODE REVIEW

**Comment by PalAditya** [comment]
@iluwatar  please note: It seems that gradle build is not compatible with java 11, which is why it errored. Please do the needful to handle the case.

Also, the travis badge in **README** should point [here](https://travis-ci.org/iluwatar/30-seconds-of-java.svg?branch=master) whereas it is pointing [here](https://travis-ci.org/iluwatar/java-snippets)

**Comment by iluwatar** [comment]
@PalAditya thanks for notifying about these issues.
- Updated to Java 11 and Gradle 5.x in #20
- Updated Travis build to use openjdk 11 in #22 
- Fixed the broken `README.md` links in commit https://github.com/iluwatar/30-seconds-of-java/commit/521d2731eb3340630e9bba5de317421998d06d21

**Comment by iluwatar** [comment]
Please merge master branch to see updated build status

**Comment by PalAditya** [comment]
> Although there is nothing wrong with HttpURLConnection I would prefer to use the new Java 11 HttpClient in the http/s related examples. Sorry for not specifying this in the task description. I will update it now.
> Related issue #24

Should I use ```var``` to preserve Java11 style or the old-school proper class names?
That is, which one is preferred? Something like
```java
for(var entry : arguments.entrySet()) {
...
}
```
or,
```java
for(Map.Entry<String, String> entry : arguments.entrySet()) {
}
```

**Comment by iluwatar** [comment]
You should prefer Java 11 style. I will also make a ticket about refactoring the existing snippets to this style.

**Comment by PalAditya** [comment]
@iluwatar Done as requested. Please review 😄

**Comment by iluwatar** [comment]
Thanks @PalAditya, well done :+1:

**Pull request merged**
