### PR TITLE
Add getCommonLetters function to string package

### PR DESCRIPTION
**Pull request by alidehkhodaei**
Hello, I added a new function to string package, I also wrote a test for that and there are java docs in the files. 
Please merge it. Thanks.

### CODE REVIEW

**Comment by alidehkhodaei** [comment]
Why it failed? Please guide me.

**Comment by iluwatar** [comment]
```
Execution failed for task ':checkLicenseMain'.
License violations were found: src/main/java/string/CommonLettersSnippet.java
```

**Comment by alidehkhodaei** [comment]
I added the missing license headers but it faild again. Excuse me, Is there another reason?

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Well done @alidehkhodaei, thank you for the contribution!

**Pull request merged**
