### PR TITLE
Add read file snippet.

### PR DESCRIPTION
**Pull request by grzesiekkedzior**
Add read file snippet.

### CODE REVIEW

**Comment by iluwatar** [comment]
The build is failing due to checkstyle errors. Please format the code according to the checkstyle rules we have in the project.

**Comment by iluwatar** [comment]
@grzesiekkedzior  Thank you for your time and valuable contribution to this repository! 👍🏻

**Comment by iluwatar** [comment]
Also @charlesfinley thanks for reviewing!

**Comment by charlesfinley** [comment]
> Also @charlesfinley thanks for reviewing!

My pleasure, happy to help out!

**Pull request merged**
