### PR TITLE
Update checkstyle to the latest and use Google checkstyle configuration

### PR DESCRIPTION
**Pull request by klurpicolo**
Objective :
Solve [issue125](https://github.com/iluwatar/30-seconds-of-java/issues/125)

Actions :
- Checkstyle updated to the latest version -> 10.3.4
- Checkstyle uses Google checks instead of the custom config -> google_checks.xml from (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
Thanks for looking into this! Here are my comments

- I think you don't need to include config/google_checks.xml since it's a built-in configuration. You can just refer to it like `google_checks.xml`.
- The build is failing since the code has not been formatted according to the new configuration

**Comment by klurpicolo** [comment]
Most of the Checkstyle errors' cause is `Missing a Javadoc comment`. Should I fix it or exclude this rule?

**Comment by iluwatar** [comment]
@klurpicolo feel free to exclude if needed. I trust your judgement.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Well done @klurpicolo, many thanks for this!

**Pull request merged**
