### PR TITLE
Add Unzip snippet

### PR DESCRIPTION
**Pull request by LordRibblesdale**

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
Please fix the CI build. Additionally I see the changes to `README.md` are missing. Please read through the [contribution instructions](https://github.com/iluwatar/30-seconds-of-java/blob/master/CONTRIBUTE.md).

**Comment by LordRibblesdale** [comment]
Is there anything else to do in order to fix CI build?
Thanks in advance!

**Comment by LordRibblesdale** [comment]
I'm available for other needed fixes for the PR.
Thanks in advance!

**Comment by LordRibblesdale** [comment]
Sorry for the inconvenience! I forgot checkstyle in testing source code

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Pull request closed without merging**
