### PR TITLE
Find maximum integer from the array

### PR DESCRIPTION
**Pull request by nishant-**
Find maximum integer from the array using reduction

### CODE REVIEW

**Comment by iluwatar** [comment]
First of all apologies. It seems that email notifications haven't been working for this repository and that's why I haven't received info about opened pull requests. I'll look into this shortly.

**Comment by iluwatar** [comment]
@nishant- the pull request looks good, but there's a conflict preventing merge. Can you please merge the changes from `master`?

**Comment by iluwatar** [comment]
@nishant-  Please add a comment to let me know when you're ready for another review

**Comment by nishant-** [comment]
Hi, @iluwatar  I have resolved the conflict. Can you please review? Thanks.

**Comment by iluwatar** [comment]
@nishant-  Thank you for your time and valuable contribution to this repository!

**Pull request merged**
