### PR TITLE
Find Levenshtein distance

### PR DESCRIPTION
**Pull request by raja-peeyush-kumar-singh**

### CODE REVIEW

**Comment by iluwatar** [comment]
First of all apologies. It seems that email notifications haven't been working for this repository and that's why I haven't received info about opened pull requests. I'll look into this shortly.

**Comment by iluwatar** [comment]
@raja-peeyush-kumar-singh  There's a conflict that prevents merge of the pull request. Please resolve the conflict by merging the changes from the `master` branch.

**Comment by iluwatar** [comment]
@raja-peeyush-kumar-singh  Please add a comment to let me know when you're ready for another review

**Comment by raja-peeyush-kumar-singh** [comment]
Have resolved the merge conflict.

**Comment by iluwatar** [comment]
@raja-peeyush-kumar-singh Thank you for your time and valuable contribution to this repository!

**Pull request merged**
